import { useState, useRef, useEffect } from "react";
import axios from "axios";
import ReactMarkdown from 'react-markdown';
import "./App.css";


const API_URL = "http://localhost:8000";

const SUGGESTIONS = [
  "Which segments have CRITICAL status?",
  "How many of those are in Clovis?",
  "What maintenance was done on those?",
  "Show all bridges and their condition",
  "What is the total maintenance cost?",
  "Which subdivision has the worst BFI?",
  "Any incomplete maintenance jobs?",
  "Average gauge in geometry surveys?",
];

function Message({ msg }) {
  const [showSQL, setShowSQL] = useState(false);
  const [showData, setShowData] = useState(false);
  const [showRAG, setShowRAG] = useState(false);

  if (msg.role === "user") {
    return (
      <div className="message user-message">
        <div className="message-bubble user-bubble">
          <span>{msg.content}</span>
        </div>
      </div>
    );
  }

  return (
    <div className="message assistant-message">
      <div className="avatar">🚂</div>
      <div className="message-content">
        <div className="answer-text">
          <ReactMarkdown>{msg.answer}</ReactMarkdown>
        </div>
        <div className="expanders">
          {/* SQL Toggle */}
          <button
            className="expander-btn"
            onClick={() => setShowSQL(!showSQL)}
          >
            🔍 {showSQL ? "Hide" : "Show"} SQL
          </button>

          {/* Data Toggle */}
          <button
            className="expander-btn"
            onClick={() => setShowData(!showData)}
          >
            📊 {showData ? "Hide" : "Show"} Data ({msg.rows} rows)
          </button>

          {/* RAG Toggle */}
          <button
            className="expander-btn"
            onClick={() => setShowRAG(!showRAG)}
          >
            📚 {showRAG ? "Hide" : "Show"} RAG Context
          </button>
        </div>

        {showSQL && (
          <div className="code-block">
            <div className="code-label">SQL Generated by Claude</div>
            <pre>{msg.sql}</pre>
          </div>
        )}

        {showData && msg.data && msg.data.length > 0 && (
          <div className="data-table-wrapper">
            <div className="code-label">Raw Data — {msg.rows} rows</div>
            <div className="table-scroll">
              <table className="data-table">
                <thead>
                  <tr>
                    {Object.keys(msg.data[0]).map((key) => (
                      <th key={key}>{key}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {msg.data.slice(0, 10).map((row, i) => (
                    <tr key={i}>
                      {Object.values(row).map((val, j) => (
                        <td key={j}>{String(val)}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
              {msg.rows > 10 && (
                <div className="table-note">
                  Showing 10 of {msg.rows} rows
                </div>
              )}
            </div>
          </div>
        )}

        {showRAG && (
          <div className="rag-block">
            <div className="code-label">RAG Context Retrieved</div>
            <div className="rag-text">{msg.rag_context}</div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function App() {
  const [messages, setMessages] = useState([]);
  const [history, setHistory] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef(null);

  // Auto scroll to bottom
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  const sendQuestion = async (question) => {
    if (!question.trim() || loading) return;

    // Add user message
    setMessages((prev) => [
      ...prev,
      { role: "user", content: question },
    ]);
    setInput("");
    setLoading(true);

    try {
      const response = await axios.post(`${API_URL}/query`, {
        question: question,
        conversation_history: history,
      });

      const data = response.data;

      // Add assistant message
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          answer: data.answer,
          sql: data.sql,
          rag_context: data.rag_context,
          rows: data.rows,
          data: data.data,
          success: data.success,
        },
      ]);

      // Update conversation history for memory
      setHistory((prev) => [
        ...prev,
        { question: question, sql: data.sql, answer: data.answer },
      ]);
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          answer: "Sorry, something went wrong. Make sure the API server is running on port 8000.",
          sql: "",
          rag_context: "",
          rows: 0,
          data: [],
          success: false,
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendQuestion(input);
    }
  };

  const clearChat = () => {
    setMessages([]);
    setHistory([]);
  };

  return (
    <div className="app">
      {/* Sidebar */}
      <div className="sidebar">
        <div className="sidebar-header">
          <span className="logo">🚂</span>
          <h2>Railway Assistant</h2>
        </div>

        <div className="sidebar-section">
          <div className="section-label">SESSION</div>
          <div className="session-info">
            Questions asked: {history.length}
          </div>
          <button className="clear-btn" onClick={clearChat}>
            🗑️ Clear Conversation
          </button>
        </div>

        <div className="sidebar-section">
          <div className="section-label">TRY ASKING</div>
          <div className="suggestions">
            {SUGGESTIONS.map((s, i) => (
              <button
                key={i}
                className="suggestion-btn"
                onClick={() => sendQuestion(s)}
                disabled={loading}
              >
                {s}
              </button>
            ))}
          </div>
        </div>

        <div className="sidebar-section">
          <div className="section-label">POWERED BY</div>
          <div className="tech-stack">
            <span className="tech-tag">Claude</span>
            <span className="tech-tag">LangGraph</span>
            <span className="tech-tag">RAG</span>
            <span className="tech-tag">Hybrid Search</span>
            <span className="tech-tag">FastAPI</span>
            <span className="tech-tag">React</span>
          </div>
        </div>
      </div>

      {/* Main chat area */}
      <div className="main">
        <div className="chat-header">
          <h1>Railway Data Assistant</h1>
          <p>Ask questions about track and ballast data in plain English</p>
        </div>

        <div className="messages">
          {messages.length === 0 && (
            <div className="empty-state">
              <div className="empty-icon">🚂</div>
              <h3>Ask anything about railway track data</h3>
              <p>Try one of the suggestions on the left, or type your own question below.</p>
            </div>
          )}

          {messages.map((msg, i) => (
            <Message key={i} msg={msg} />
          ))}

          {loading && (
            <div className="message assistant-message">
              <div className="avatar">🚂</div>
              <div className="loading-bubble">
                <span className="dot"></span>
                <span className="dot"></span>
                <span className="dot"></span>
              </div>
            </div>
          )}

          <div ref={bottomRef} />
        </div>

        {/* Input area */}
        <div className="input-area">
          <div className="input-wrapper">
            <textarea
              className="input-box"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask a question about railway data... (Enter to send)"
              rows={1}
              disabled={loading}
            />
            <button
              className="send-btn"
              onClick={() => sendQuestion(input)}
              disabled={loading || !input.trim()}
            >
              {loading ? "..." : "➤"}
            </button>
          </div>
          <div className="input-hint">
            Press Enter to send · Shift+Enter for new line
          </div>
        </div>
      </div>
    </div>
  );
}